DROP DATABASE IF EXISTS codeup_test_db;
CREATE DATABASE codeup_test_db;
USE codeup_test_db;

DROP TABLE IF EXISTS albums;
CREATE TABLE albums (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ARTIST VARCHAR(240),
  NAME VARCHAR(240) NOT NULL,
  RELEASE_DATE INT UNSIGNED,
  SALES FLOAT,
  GENRE VARCHAR(240),
  PRIMARY KEY (id)
)